spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/livrariadankicode?createDatabaseIfNotExist=true
    username: root
    password: Gatao-04

  jpa:
    show-sql: true